addSbtPlugin("com.localytics"      % "sbt-dynamodb"              % "2.0.3")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest"               % "0.9.5")
addSbtPlugin("com.47deg"           % "sbt-microsites"            % "1.0.2")
addSbtPlugin("com.geirsson"        % "sbt-ci-release"            % "1.4.31")
// addSbtPlugin("org.scoverage"       % "sbt-scoverage"             % "1.6.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"              % "2.3.0")
addSbtPlugin("ch.epfl.scala"       % "sbt-bloop"                 % "1.3.5")
addSbtPlugin("com.github.cb372"    % "sbt-explicit-dependencies" % "0.2.11")
addSbtPlugin("de.heikoseeberger"   % "sbt-header"                % "5.3.1")
addSbtPlugin("ch.epfl.lamp"        % "sbt-dotty"                 % "0.3.4")
