addSbtPlugin("com.localytics"    % "sbt-dynamodb"              % "2.0.3")
addSbtPlugin("com.47deg"         % "sbt-microsites"            % "1.3.0")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"            % "1.5.5")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"             % "1.6.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"              % "2.4.2")
addSbtPlugin("ch.epfl.scala"     % "sbt-bloop"                 % "1.4.5")
addSbtPlugin("com.github.cb372"  % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("de.heikoseeberger" % "sbt-header"                % "5.6.0")
